"""recriando_estrutura

Revision ID: 3c6040e082f6
Revises: c5217da3e88a
Create Date: 2026-05-08 22:13:02.367154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c6040e082f6'
down_revision: Union[str, None] = 'c5217da3e88a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_estoque_id_estoque', table_name='estoque')
    op.drop_table('estoque')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque',
    sa.Column('id_estoque', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo_residuo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('quantidade_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ultima_atualizacao', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_estoque', name='estoque_pkey'),
    sa.UniqueConstraint('tipo_residuo', name='estoque_tipo_residuo_key')
    )
    op.create_index('ix_estoque_id_estoque', 'estoque', ['id_estoque'], unique=False)
    # ### end Alembic commands ###
