"""Adiciona nullable=False ao modelo Usuario

Revision ID: a4a618c0a0da
Revises: cbd3c03713de
Create Date: 2026-05-15 18:11:12.514102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a618c0a0da'
down_revision: Union[str, None] = 'cbd3c03713de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuario', 'telefone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuario', 'senha_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'senha_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuario', 'telefone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuario', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
