"""adicionar tabela estoque

Revision ID: c5217da3e88a
Revises: b0a7784f38c1
Create Date: 2026-05-08 21:05:10.795160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5217da3e88a'
down_revision: Union[str, None] = 'b0a7784f38c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque',
    sa.Column('id_estoque', sa.Integer(), nullable=False),
    sa.Column('tipo_residuo', sa.String(length=50), nullable=False),
    sa.Column('quantidade_total', sa.Float(), nullable=True),
    sa.Column('ultima_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_estoque'),
    sa.UniqueConstraint('tipo_residuo')
    )
    op.create_index(op.f('ix_estoque_id_estoque'), 'estoque', ['id_estoque'], unique=False)
    op.drop_table('campanha')
    op.drop_table('ponto_de_coleta')
    op.drop_table('coleta')
    op.drop_table('pontuacao')
    op.add_column('descarte', sa.Column('usuario_lat', sa.Float(), nullable=True))
    op.add_column('descarte', sa.Column('usuario_long', sa.Float(), nullable=True))
    op.add_column('descarte', sa.Column('ponto_lat', sa.Float(), nullable=True))
    op.add_column('descarte', sa.Column('ponto_long', sa.Float(), nullable=True))
    op.alter_column('descarte', 'data_desc',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('descarte', 'tipo_residuo',
               existing_type=postgresql.ENUM('papelao', 'plastico', 'metal', 'papel', 'cobre', 'vidro', 'pilhas', 'baterias', 'aluminio', 'garrafa pet', name='tipo_residuo_enum'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('descarte', 'observacao',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_descarte_id_descarte'), 'descarte', ['id_descarte'], unique=False)
    op.drop_constraint('descarte_usuario_id_fkey', 'descarte', type_='foreignkey')
    op.alter_column('endereco', 'rua',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('endereco', 'bairro',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('endereco', 'numero',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('endereco', 'cep',
               existing_type=sa.CHAR(length=8),
               type_=sa.String(),
               nullable=True)
    op.alter_column('endereco', 'cidade',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_endereco_id_end'), 'endereco', ['id_end'], unique=False)
    op.add_column('usuario', sa.Column('role', sa.String(), server_default='usuario', nullable=False))
    op.alter_column('usuario', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('usuario', 'telefone',
               existing_type=sa.CHAR(length=11),
               type_=sa.String(),
               nullable=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_unique_constraint(None, 'usuario', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.alter_column('usuario', 'telefone',
               existing_type=sa.String(),
               type_=sa.CHAR(length=11),
               nullable=False)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('usuario', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('usuario', 'role')
    op.drop_index(op.f('ix_endereco_id_end'), table_name='endereco')
    op.alter_column('endereco', 'cidade',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('endereco', 'cep',
               existing_type=sa.String(),
               type_=sa.CHAR(length=8),
               nullable=False)
    op.alter_column('endereco', 'numero',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('endereco', 'bairro',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('endereco', 'rua',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_foreign_key('descarte_usuario_id_fkey', 'descarte', 'usuario', ['usuario_id'], ['id'])
    op.drop_index(op.f('ix_descarte_id_descarte'), table_name='descarte')
    op.alter_column('descarte', 'observacao',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('descarte', 'tipo_residuo',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('papelao', 'plastico', 'metal', 'papel', 'cobre', 'vidro', 'pilhas', 'baterias', 'aluminio', 'garrafa pet', name='tipo_residuo_enum'),
               existing_nullable=True)
    op.alter_column('descarte', 'data_desc',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('descarte', 'ponto_long')
    op.drop_column('descarte', 'ponto_lat')
    op.drop_column('descarte', 'usuario_long')
    op.drop_column('descarte', 'usuario_lat')
    op.create_table('pontuacao',
    sa.Column('id_pontuacao', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pontos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_reg', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='pontuacao_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id_pontuacao', name='pontuacao_pkey')
    )
    op.create_table('coleta',
    sa.Column('id_coleta', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_coleta', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status_col', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('volume_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('observacao', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_coleta', name='coleta_pkey')
    )
    op.create_table('ponto_de_coleta',
    sa.Column('id_ponto', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('capacidade', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('endereco', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['endereco'], ['endereco.id_end'], name='ponto_de_coleta_endereco_fkey'),
    sa.PrimaryKeyConstraint('id_ponto', name='ponto_de_coleta_pkey')
    )
    op.create_table('campanha',
    sa.Column('id_campanha', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('desc_camp', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('data_inic', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data_fim', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_campanha', name='campanha_pkey')
    )
    op.drop_index(op.f('ix_estoque_id_estoque'), table_name='estoque')
    op.drop_table('estoque')
    # ### end Alembic commands ###
